// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVoqTVuw8wyYIxg7Qg6GjnUMta1DarfvE',
    appId: '1:601051449298:web:37f34877c85675ca53ea0b',
    messagingSenderId: '601051449298',
    projectId: 'chatappflutter-dd707',
    authDomain: 'chatappflutter-dd707.firebaseapp.com',
    storageBucket: 'chatappflutter-dd707.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOaB9YMBiNPc8P0eU3o_18PNXzXGI4_ZM',
    appId: '1:601051449298:android:c87dcf8cb1783a5d53ea0b',
    messagingSenderId: '601051449298',
    projectId: 'chatappflutter-dd707',
    storageBucket: 'chatappflutter-dd707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiVJD0nXYbimIngjSLgNm8OEp3Z1Kv9YY',
    appId: '1:601051449298:ios:f41528bf3cbd514753ea0b',
    messagingSenderId: '601051449298',
    projectId: 'chatappflutter-dd707',
    storageBucket: 'chatappflutter-dd707.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiVJD0nXYbimIngjSLgNm8OEp3Z1Kv9YY',
    appId: '1:601051449298:ios:f41528bf3cbd514753ea0b',
    messagingSenderId: '601051449298',
    projectId: 'chatappflutter-dd707',
    storageBucket: 'chatappflutter-dd707.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVoqTVuw8wyYIxg7Qg6GjnUMta1DarfvE',
    appId: '1:601051449298:web:e9e1da96050d6e1053ea0b',
    messagingSenderId: '601051449298',
    projectId: 'chatappflutter-dd707',
    authDomain: 'chatappflutter-dd707.firebaseapp.com',
    storageBucket: 'chatappflutter-dd707.appspot.com',
  );
}
